#!/usr/bin/python3
# store user input
age = eval(input("Please enter your age: "))
# If age is 5 Go to Kindergarten 
if age < 5:
    print("Too young for school")
# Ages 6 through 17 goes to grades 1 through 12
elif age == 5:
    print("Goes to Kindegarten")
# if age is greater then 17 say got to college
elif (age > 5) and (age <= 17):
    grade = age - 5
    print("Go to {} grade".format(grade))
else:
    print("Go to college")
# Try to complete with 10 or less lines
